platformName: Android
platformVersion: '13'
deviceName: 三星
uuid: RFCW203YCJW
app: com.ccbhome.lanhai_3.4.9_129.apk
appPackage: com.ccbhome.lanhai
appActivate: com.ccbhome.lanhai.ui.activity.SplashActivity
unicodeKeyboard: True
resetKeyboard: True
newCommandTimeout: 60

host: 127.0.0.1
port: '4723'